[server]
hostname = "localhost"
port = 8181
secure = true
keyFile = "src/dev_certs/server.key"
certFile = "src/dev_certs/server.crt"

[repo]
org = "elastic"
name = "cloud"

[es]
uri = "https://elastic:password@ac09797ae4a1485db622c04ee7a99979.192.168.42.42.xip.io:9243/"

[jwt]
secret = false
issuer = "skunksheet"

[session]
secret = false

[logging]
level = "debug"

[github]
appId = false
appSecret = false
botAccountToken = false
callbackPath = "/auth/github/callback"
